# https://docs.github.com/en/actions/using-jobs/assigning-permissions-to-jobs#overview
name: Disable GITHUB_TOKEN
on:
  push:
  workflow_dispatch:
permissions: {}  
jobs:
  log-secret:
    runs-on: ubuntu-latest
    steps:
      - name: Print my secret
        run: |
          echo ${{ secrets.MY_SECRET }} # prints ***
          echo ${{ secrets.MY_SECRET }} | sed -e 's/\(.\)/\1 /g' # prints the secrets with spaces
